{
 "title": "PDU",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdu_state{job=\"PDU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current draw",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdu_live_Current{job=\"PDU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdu_temp{job=\"PDU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdu_hum{job=\"PDU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Ampere",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "pdu_live_Current{job=\"PDU\"}",
     "legendFormat": "Ampere"
    }
   ]
  },
  {
   "title": "Outlet 1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdu_Outlet1{job=\"PDU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outlet 2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdu_Outlet2{job=\"PDU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outlet 3",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdu_Outlet3{job=\"PDU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outlet 4",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdu_Outlet4{job=\"PDU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outlet 5",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdu_Outlet5{job=\"PDU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outlet 6",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdu_Outlet6{job=\"PDU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outlet 7",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdu_Outlet7{job=\"PDU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outlet 8",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdu_Outlet8{job=\"PDU\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}